config/routes.rb
Tweetfortweet::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  root :to => 'home#index'
  match 'dashboard' => 'dashboard#index'
  match 'update_status' => 'twitter_api#update_status'
  match 'retweet' => 'twitter_api#retweet'

end

app/models/twitter_job.rb
class TwitterJob < ActiveRecord::Base
  belongs_to :user

  validates :tweet_id, :tweet_text, :presence => :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :registerable, :rememberable, :trackable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :remember_me, :provider, :uid

  has_many :twitter_jobs, :dependent => :destroy

  serialize :auth_info
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    @our_tweets = @user.twitter_jobs
    @other_tweets = TwitterJob.where("user_id <> ?", @user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    redirect_to dashboard_path if current_user
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.find_or_initialize_by_uid(request.env["omniauth.auth"]["uid"])

    if @user.persisted?
      flash[:success] = "Successfully signed in!"
    else
      @user.uid = request.env["omniauth.auth"]["uid"]
      @user.provider = request.env["omniauth.auth"]["provider"]
      @user.auth_info = request.env["omniauth.auth"]
      @user.save!
      flash[:success] = "Successfully signed up!"
    end
    sign_in @user
    redirect_to dashboard_url
  end
end

app/controllers/twitter_api_controller.rb
class TwitterApiController < ApplicationController
  before_filter :get_client

  def get_client
    @twitter_client = Twitter::Client.new
        @twitter_client.configure do |config|
          config.oauth_token = current_user.auth_info["credentials"]["token"]
          config.oauth_token_secret = current_user.auth_info["credentials"]["secret"]
        end
  end

  def update_status
    status = @twitter_client.update(params[:message])
    current_user.twitter_jobs.create(:tweet_id => status[:id], :tweet_text => status[:text])

    flash[:notice] = "Update status with: #{params[:message]}"
    redirect_to dashboard_path
  end

  def retweet
    @twitter_client.retweet(params[:tweet_id])
    twitter_job = TwitterJob.find_by_tweet_id(params[:tweet_id])
    flash[:notice] = "Retweeted id: #{twitter_job.tweet_id}, text: #{twitter_job.tweet_text}"
    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/twitter_api_helper.rb
module TwitterApiHelper
end

app/views/dashboard/index.html.haml
.row
  .span5
    %h1= "Hello, #{current_user.auth_info["info"]["name"]}"
    %h2= "Your credits: #{current_user.credits}"
.row
  .span6
    %h2 Your tweets
    %table.table.table-striped
      %thead
        %tr
          %th
            Tweet ID
          %th
            Tweet Text
      %tbody
        - @our_tweets.each do |tweet|
          %tr
            %td= tweet.tweet_id
            %td= tweet.tweet_text

  .span6
    %h2 Other tweets
    %table.table.table-striped
      %thead
        %tr
          %th
            Twitter User
          %th
            Tweet Text
      %tbody
        - @other_tweets.each do |tweet|
          %tr
            %td= tweet.user.auth_info.try(:[], "info").try(:[], "name")
            %td
              = tweet.tweet_text
              .pull-right
                = link_to "Retweet", retweet_path(tweet_id: tweet.tweet_id)
.row
  .span5
    = form_tag update_status_path do
      = text_field_tag :message
      = submit_tag

app/views/home/index.html.haml
.row
  .span12
    .hero-unit
      %h1
        Tweet for Tweet
      %p
        Automated Twitter Retweet Exchange
      %p
        = link_to user_omniauth_authorize_path(:twitter), :class => "btn btn-primary btn-large" do
          %i.icon-twitter-sign
          Sign in with Twitter

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tweet For Tweet
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "http://platform.twitter.com/widgets.js"
    = csrf_meta_tags

  %body
    - if current_user
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            = link_to "TweetForTweet", "#", :class => "brand"
            %ul.nav.pull-right
              %li= link_to "Sign out", logout_path, :method => :delete

    .container
      - flash.each do |name, msg|
        .row
          .span4
            = content_tag :div, :class => "alert flash_#{name}" do
              = link_to "×", "#", :data => {dismiss: "alert"}, :class => "close"
              = msg
      = yield

    = yield(:js_footer)